name: Deploy new shape classification service upon merge to master

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      NEPTUNE_PROJECT_NAME: ${{ secrets.NEPTUNE_PROJECT_NAME }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}         
  
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup main branch environment and run experiment to get reference and model file
        id: experiment_main
        run: |
          pip3 install -r requirements.txt
          export NEPTUNE_EXPERIMENT_TAG_ID=$(uuidgen)
          python train.py --rfc -v --upload > log.txt
          text=$(cat log.txt | grep -v Evaluating)
          echo ::set-output name=url::$text

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
          repository: piotrtomaszewski/shape_prediction
          tags: latest
      - name: Create a comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            ${{ steps.experiment_main.outputs.url }}
            ${{ steps.docker_build.outputs.digest }}
          