name: Pull request actions

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - 'models/**'

jobs:
  compare-experiments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      NEPTUNE_PROJECT_NAME: ${{ secrets.NEPTUNE_PROJECT_NAME }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}         
  
      - name: Checkout pull request branch
        uses: actions/checkout@v2        

      - name: Setup pull request branch environment and run experiment
        id: experiment_pr
        run: |
          pip3 install -r requirements_build.txt
          export NEPTUNE_EXPERIMENT_TAG_ID=$(uuidgen)
          python train.py --rfc --upload > log.txt
          text=$(cat log.txt | grep -v Evaluating)
          rm models/default/*.zip
          echo ::set-output name=url::$text
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: ${{ steps.experiment_pr.outputs.url }}
      - name: Create a comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            ${{ steps.experiment_pr.outputs.url }}
          